// Generated by gencpp from file sim_uav/land_aruco.msg
// DO NOT EDIT!


#ifndef SIM_UAV_MESSAGE_LAND_ARUCO_H
#define SIM_UAV_MESSAGE_LAND_ARUCO_H

#include <ros/service_traits.h>


#include <sim_uav/land_arucoRequest.h>
#include <sim_uav/land_arucoResponse.h>


namespace sim_uav
{

struct land_aruco
{

typedef land_arucoRequest Request;
typedef land_arucoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct land_aruco
} // namespace sim_uav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sim_uav::land_aruco > {
  static const char* value()
  {
    return "02fd582894f05f0c4b5cc3fc3ea23d3d";
  }

  static const char* value(const ::sim_uav::land_aruco&) { return value(); }
};

template<>
struct DataType< ::sim_uav::land_aruco > {
  static const char* value()
  {
    return "sim_uav/land_aruco";
  }

  static const char* value(const ::sim_uav::land_aruco&) { return value(); }
};


// service_traits::MD5Sum< ::sim_uav::land_arucoRequest> should match
// service_traits::MD5Sum< ::sim_uav::land_aruco >
template<>
struct MD5Sum< ::sim_uav::land_arucoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sim_uav::land_aruco >::value();
  }
  static const char* value(const ::sim_uav::land_arucoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sim_uav::land_arucoRequest> should match
// service_traits::DataType< ::sim_uav::land_aruco >
template<>
struct DataType< ::sim_uav::land_arucoRequest>
{
  static const char* value()
  {
    return DataType< ::sim_uav::land_aruco >::value();
  }
  static const char* value(const ::sim_uav::land_arucoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sim_uav::land_arucoResponse> should match
// service_traits::MD5Sum< ::sim_uav::land_aruco >
template<>
struct MD5Sum< ::sim_uav::land_arucoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sim_uav::land_aruco >::value();
  }
  static const char* value(const ::sim_uav::land_arucoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sim_uav::land_arucoResponse> should match
// service_traits::DataType< ::sim_uav::land_aruco >
template<>
struct DataType< ::sim_uav::land_arucoResponse>
{
  static const char* value()
  {
    return DataType< ::sim_uav::land_aruco >::value();
  }
  static const char* value(const ::sim_uav::land_arucoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIM_UAV_MESSAGE_LAND_ARUCO_H
