// Generated by gencpp from file sim_uav/target_global_pos.msg
// DO NOT EDIT!


#ifndef SIM_UAV_MESSAGE_TARGET_GLOBAL_POS_H
#define SIM_UAV_MESSAGE_TARGET_GLOBAL_POS_H

#include <ros/service_traits.h>


#include <sim_uav/target_global_posRequest.h>
#include <sim_uav/target_global_posResponse.h>


namespace sim_uav
{

struct target_global_pos
{

typedef target_global_posRequest Request;
typedef target_global_posResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct target_global_pos
} // namespace sim_uav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sim_uav::target_global_pos > {
  static const char* value()
  {
    return "98e43780eebfdb5a8104168ac5430b7a";
  }

  static const char* value(const ::sim_uav::target_global_pos&) { return value(); }
};

template<>
struct DataType< ::sim_uav::target_global_pos > {
  static const char* value()
  {
    return "sim_uav/target_global_pos";
  }

  static const char* value(const ::sim_uav::target_global_pos&) { return value(); }
};


// service_traits::MD5Sum< ::sim_uav::target_global_posRequest> should match
// service_traits::MD5Sum< ::sim_uav::target_global_pos >
template<>
struct MD5Sum< ::sim_uav::target_global_posRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sim_uav::target_global_pos >::value();
  }
  static const char* value(const ::sim_uav::target_global_posRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sim_uav::target_global_posRequest> should match
// service_traits::DataType< ::sim_uav::target_global_pos >
template<>
struct DataType< ::sim_uav::target_global_posRequest>
{
  static const char* value()
  {
    return DataType< ::sim_uav::target_global_pos >::value();
  }
  static const char* value(const ::sim_uav::target_global_posRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sim_uav::target_global_posResponse> should match
// service_traits::MD5Sum< ::sim_uav::target_global_pos >
template<>
struct MD5Sum< ::sim_uav::target_global_posResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sim_uav::target_global_pos >::value();
  }
  static const char* value(const ::sim_uav::target_global_posResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sim_uav::target_global_posResponse> should match
// service_traits::DataType< ::sim_uav::target_global_pos >
template<>
struct DataType< ::sim_uav::target_global_posResponse>
{
  static const char* value()
  {
    return DataType< ::sim_uav::target_global_pos >::value();
  }
  static const char* value(const ::sim_uav::target_global_posResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIM_UAV_MESSAGE_TARGET_GLOBAL_POS_H
