// Generated by gencpp from file sim_uav/target_local_pos.msg
// DO NOT EDIT!


#ifndef SIM_UAV_MESSAGE_TARGET_LOCAL_POS_H
#define SIM_UAV_MESSAGE_TARGET_LOCAL_POS_H

#include <ros/service_traits.h>


#include <sim_uav/target_local_posRequest.h>
#include <sim_uav/target_local_posResponse.h>


namespace sim_uav
{

struct target_local_pos
{

typedef target_local_posRequest Request;
typedef target_local_posResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct target_local_pos
} // namespace sim_uav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sim_uav::target_local_pos > {
  static const char* value()
  {
    return "fb2d2cec436c25bb2c92caf8218fe6ff";
  }

  static const char* value(const ::sim_uav::target_local_pos&) { return value(); }
};

template<>
struct DataType< ::sim_uav::target_local_pos > {
  static const char* value()
  {
    return "sim_uav/target_local_pos";
  }

  static const char* value(const ::sim_uav::target_local_pos&) { return value(); }
};


// service_traits::MD5Sum< ::sim_uav::target_local_posRequest> should match
// service_traits::MD5Sum< ::sim_uav::target_local_pos >
template<>
struct MD5Sum< ::sim_uav::target_local_posRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sim_uav::target_local_pos >::value();
  }
  static const char* value(const ::sim_uav::target_local_posRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sim_uav::target_local_posRequest> should match
// service_traits::DataType< ::sim_uav::target_local_pos >
template<>
struct DataType< ::sim_uav::target_local_posRequest>
{
  static const char* value()
  {
    return DataType< ::sim_uav::target_local_pos >::value();
  }
  static const char* value(const ::sim_uav::target_local_posRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sim_uav::target_local_posResponse> should match
// service_traits::MD5Sum< ::sim_uav::target_local_pos >
template<>
struct MD5Sum< ::sim_uav::target_local_posResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sim_uav::target_local_pos >::value();
  }
  static const char* value(const ::sim_uav::target_local_posResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sim_uav::target_local_posResponse> should match
// service_traits::DataType< ::sim_uav::target_local_pos >
template<>
struct DataType< ::sim_uav::target_local_posResponse>
{
  static const char* value()
  {
    return DataType< ::sim_uav::target_local_pos >::value();
  }
  static const char* value(const ::sim_uav::target_local_posResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIM_UAV_MESSAGE_TARGET_LOCAL_POS_H
